[package]
name = "emigui-miniquad"
version = "0.1.0"
authors = ["Logachev Fedor <not.fl3@gmail.com >"]
edition = "2018"

[dependencies]
emigui = { git = "https://github.com/emilk/emigui.git", rev="7cd8ac2bb", package = "emigui" }

miniquad = "0.2"

